apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: {{ .Values.client.replicaCount }}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image }}:{{ .Values.client.tag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        env:
        - name: BACKEND_URL
          value: {{ .Values.back.url }}
        ports:
        - containerPort: 3000