apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: {{ .Values.client.nodePort }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: client