apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: etangdesapplis/demo-site-front-admin
        imagePullPolicy: Always
        ports:
        - containerPort: 3000