apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 32019
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: admin