apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app: back
spec:
  #type: NodePort
  ports:
  - port: 5000
    #nodePort: 32017
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: back