apiVersion: v1
kind: Service
metadata:
  name: back
  labels:
    app: back
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32020
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: back